### ISSUE TITLE
compute about attention

### ISSUE THREAD

**Issue by bobzhang208** [sramshetty/mixture-of-depths#1]
It seems that in your code all the token in a sequence are put into the transformer (attention and ffn) block?

**Comment by sramshetty** [comment]
Hi Bob, that is correct, however within the transformer block we use a router to pick the top-k tokens that should actually be passed through attention and ffn. You can find that [here](https://github.com/sramshetty/mixture-of-depths/blob/main/mixture_of_depths/routing_transformer.py#L296). Hopefully, that answers your question otherwise happy to answer anything else.

Also if you catch anything wrong, please don't hesitate to let me know so that I can fix it! Thanks!

**Comment by bobzhang208** [comment]
but according to your code that all the the tokens is computed which will not reduce the FLOPS. In my view, the MOD will only put n tokens in attention and FFN(which n is smaller then the total seq_lens). Is it right?

**Comment by sramshetty** [comment]
If you are talking about inference then I think this is also what #2 is talking about. Thanks for catching this, I'll try to fix it soon.

**Comment by bobzhang208** [comment]
yes, i agree with the point in the issue you referenced. and i also mean while inference there will be a prefill stage isn't it? during that a sequence with n token will be input to model at the same time, and according to the description in the paper, the router before transformer block will make sure that top-k tokens in the given n tokens should be put into the transformer block,and that will reduce the flops in my view

**Comment by bobzhang208** [comment]
```

            y = x.clone()
            x = x.gather(
                dim=1,
                index=repeat(sorted_indices, 'b s -> b s d', d=self.dim)
            )
            seq_len = x.size(1)
            freqs_cis = freqs_cis[:seq_len]

        if seq_len > 1:
            mask = torch.full(
                (seq_len, seq_len), float("-inf"), device=x.device
            )
            mask = torch.triu(mask, diagonal=1)

            # When performing key-value caching, we compute the attention scores
            # only for the new sequence. Thus, the matrix of scores is of size
            # (seqlen, cache_len + seqlen), and the only masked entries are (i, j) for
            # j > cache_len + i, since row i corresponds to token cache_len + i.
            mask = torch.hstack([
                torch.zeros((seq_len, start_pos), device=x.device),
                mask
            ]).type_as(x)

        h = x + self.attention(
            self.attention_norm(x), start_pos, freqs_cis, mask
        )

```


the x which put to attention seems has the same shape with the normal transformer in llama

**Comment by sramshetty** [comment]
I see, that initial stage I get the sequence lengths as follows for some arbitrary text:
```
501
256
501
256
501
256
1
1
...
```
Where 501 is the original sequence length but router blocks only pass the top-k tokens (256 in my case). I believe this makes sense because the routing is done every other layer, therefore we see 256 3 times out of the 6 layers (I print at each layer). You're right that if the other layers were also routed then we could reduce FLOPS, but the paper found this configuration the best. 

As for inference after the "prefill" stage, I hope to look into it soon.

Hopefully, I was able to address your concerns/questions, thanks for taking the time to look over the code!
